#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["httpx"]
# ///
"""Fetch RAF airfield locations from OpenStreetMap via Overpass API.

Queries for military=airfield with operator matching RAF/Royal Air Force,
then writes bases.js for the frontend. A handful of well-known stations
tagged differently in OSM and overseas bases are added manually.
"""

import json
import httpx

OVERPASS_URL = "https://overpass-api.de/api/interpreter"

QUERY = """
[out:json][timeout:30];
(
  node["military"="airfield"]["operator"~"Royal Air Force|RAF",i];
  way["military"="airfield"]["operator"~"Royal Air Force|RAF",i];
  relation["military"="airfield"]["operator"~"Royal Air Force|RAF",i];
);
out center tags;
"""

# Stations not tagged military=airfield in OSM, or overseas
EXTRA_BASES = [
    {"name": "RAF Lossiemouth",  "coords": [-3.3392, 57.7052], "icao": "EGQS"},
    {"name": "RAF Waddington",   "coords": [-0.5238, 53.1662], "icao": "EGXW"},
    {"name": "RAF Valley",       "coords": [-4.5354, 53.2481], "icao": "EGOV"},
    {"name": "RAF Scampton",     "coords": [-0.5508, 53.3078], "icao": "EGXP"},
    {"name": "RAF Honington",    "coords": [0.7727, 52.3426],  "icao": "EGXH"},
    {"name": "RAF Fylingdales",  "coords": [-0.6703, 54.3615]},
    {"name": "RAF High Wycombe", "coords": [-0.8007, 51.6357]},
    {"name": "RAF Digby",        "coords": [-0.4161, 53.0448], "icao": "EGXD"},
    {"name": "RAF Akrotiri",     "coords": [32.9879, 34.5904], "icao": "LCRA"},
    {"name": "RAF Gibraltar",    "coords": [-5.3496, 36.1512], "icao": "LXGB"},
]


def main():
    resp = httpx.get(OVERPASS_URL, params={"data": QUERY}, timeout=60)
    resp.raise_for_status()
    data = resp.json()

    bases = []
    seen = set()

    for el in data["elements"]:
        tags = el.get("tags", {})
        name = tags.get("name", "")
        if not name or name in seen:
            continue
        # Skip disused
        if "disused:aeroway" in tags:
            continue
        seen.add(name)
        lat = el.get("lat") or el.get("center", {}).get("lat")
        lon = el.get("lon") or el.get("center", {}).get("lon")
        entry = {"name": name, "coords": [round(lon, 4), round(lat, 4)]}
        icao = tags.get("icao", "")
        if icao:
            entry["icao"] = icao
        bases.append(entry)

    for extra in EXTRA_BASES:
        if extra["name"] not in seen:
            seen.add(extra["name"])
            bases.append(extra)

    bases.sort(key=lambda b: b["name"])

    # Write bases.js
    lines = [
        "// RAF stations — from OpenStreetMap (Overpass API) + manual additions.",
        "// Generated by scripts/fetch_bases.py. Coordinates are [lon, lat] per GeoJSON.",
        "",
        "const RAF_BASES = [",
    ]
    for b in bases:
        icao_str = f', icao: {json.dumps(b["icao"])}' if "icao" in b else ""
        lines.append(f'  {{ name: {json.dumps(b["name"])}, coords: {b["coords"]}{icao_str} }},')
    lines.append("];")
    lines.append("")

    with open("bases.js", "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(bases)} bases → bases.js")


main()
